services:
  - type: web
    name: backend
    env: node
    nodeVersion: 20.x
    buildCommand: |
      rm -rf node_modules
      yarn install
      yarn prisma generate
    startCommand: |
      yarn start